version: '3'

services:
  phinx:
    build: .
    volumes:
      - .:/the-employees

  database:
    image: mysql:5.7
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: very-strong!
      MYSQL_DATABASE: the_employees_db
      
